#pragma once

#include <cstdint>

#include <string>

namespace ecs
{
class World;
class ComponentManager;
class TagManager;

struct Entity {
	uint32_t id;
	uint32_t version;
};

struct ComponentId {
	uint32_t id;
};

struct TagId {
	uint32_t id;
};

struct TypeTraits {
	void (*const assure)(Entity entity, ComponentManager *manager);
	void *(*const access)(Entity entity, ComponentManager *manager);
	void *(*const add)(Entity entity, ComponentManager *manager);
	void *(*const set_copy)(Entity entity, ComponentManager *manager, const void *ptr);
	void *(*const set_move)(Entity entity, ComponentManager *manager, void *mov_ptr);
	void *(*const get)(Entity entity, const ComponentManager *manager);
	void (*const remove)(Entity entity, ComponentManager *manager);

	void (*const execute_observers_add)(Entity entity, ComponentManager *manager);
	void (*const execute_observers_set)(Entity entity, ComponentManager *manager);
	void (*const execute_observers_remove)(Entity entity, ComponentManager *manager);

	void (*const move_to_empty)(void *src, void *dst);
	void (*const copy_to_empty)(const void *src, void *dst);
	void (*const move_to_existing)(void *src, void *dst);
	void (*const copy_to_existing)(const void *src, void *dst);
	void (*const construct)(void *ptr);
	void (*const destruct)(void *ptr);

	void (*const serialize)(struct serializer &ar, const void *ptr);
	void (*const deserialize)(struct deserializer &ar, void *ptr);

	const char *type_name;
	const std::string name;
	const uint32_t bytes;
	const uint32_t alignement;
	const bool poco;
	const ComponentId component_id;
};

struct TagTypeTraits {
	const char *type_name;
	const std::string name;
	const TagId tag_id;
};
}

struct ExamplePosition {
	float x, y, z;

	// generated by macro ECS_TYPE_TRAITS_HEADER(TYPE_NAME, ALIGNEMENT, POCO)
	using TypeTraits = ecs::TypeTraits;
	using World = ecs::World;
	using ComponentManager = ecs::ComponentManager;
	using ComponentId = ecs::ComponentId;
	using Entity = ecs::Entity;
	struct TypeTraitsInline {
		static const TypeTraits *GetTypeTraits();

		const static inline char *type_name = "ExamplePosition";
		const static inline std::string name;
		const static inline uint32_t bytes = 12;
		const static inline uint32_t alignement = 4;
		const static inline bool poco = true;
		const static inline ComponentId component_id = {0};

		struct Typed {
			using T = ExamplePosition;

			static void assure(Entity entity, ComponentManager *manager);
			static T &access(Entity entity, ComponentManager *manager);
			static T &add(Entity entity, ComponentManager *manager);
			static T &set(Entity entity, ComponentManager *manager, const T &val);
			static T &set(Entity entity, ComponentManager *manager, T &&mov_val);
			static T *get(Entity entity, const ComponentManager *manager);
			static void remove(Entity entity, ComponentManager *manager);

			static void execute_observers_add(Entity entity, ComponentManager *manager);
			static void execute_observers_set(Entity entity, ComponentManager *manager);
			static void execute_observers_remove(Entity entity, ComponentManager *manager);

			static void move_to_empty(T &&src, T &dst);
			static void copy_to_empty(const T &src, T &dst);
			static void move_to_existing(T &&src, T &dst);
			static void copy_to_existing(const T &src, T *dst);
			static void construct(T *ptr);
			static void destruct(T *ptr);

			static void serialize(struct serializer &ar, const T *ptr);
			static void deserialize(struct deserializer &ar, T *ptr);
		};

		struct Void {
			static void assure(Entity entity, ComponentManager *manager);
			static void *access(Entity entity, ComponentManager *manager);
			static void *add(Entity entity, ComponentManager *manager);
			static void *set_copy(Entity entity, ComponentManager *manager, const void *ptr);
			static void *set_move(Entity entity, ComponentManager *manager, void *mov_ptr);
			static void *get(Entity entity, const ComponentManager *manager);
			static void remove(Entity entity, ComponentManager *manager);

			static void execute_observers_add(Entity entity, ComponentManager *manager);
			static void execute_observers_set(Entity entity, ComponentManager *manager);
			static void execute_observers_remove(Entity entity, ComponentManager *manager);

			static void move_to_empty(void *src, void *dst);
			static void copy_to_empty(const void *src, void *dst);
			static void move_to_existing(void *src, void *dst);
			static void copy_to_existing(const void *src, void *dst);
			static void construct(void *ptr);
			static void destruct(void *ptr);

			static void serialize(struct serializer &ar, const void *ptr);
			static void deserialize(struct deserializer &ar, void *ptr);
		};
	};
	void serialize(struct serializer &ar) const;
	void deserialize(struct deserializer &ar);
};

struct ExampleTagPlayer {
	// generated by macro ECS_TYPE_TRAITS_HEADER(TYPE_NAME, ALIGNEMENT, POCO)
	using TagTypeTraits = ecs::TagTypeTraits;
	using World = ecs::World;
	using TagManager = ecs::TagManager;
	using TagId = ecs::TagId;
	using Entity = ecs::Entity;
	struct TagTypeTraitsInline {
		static const TagTypeTraits *GetTagTypeTraits();

		const static inline char *type_name = "ExampleTagPlayer";
		const static inline std::string name;
		static TagId component_id;
	};
};


