#pragma once

#include "components_header.hpp"

struct ExamplePosition {
	float x, y, z;
	
	ECS_TYPE_TRAITS_HEADER(ExamplePosition, {"EP", 3}, true, 4);
};

struct ExampleTagPlayer {
	// generated by macro ECS_TYPE_TRAITS_HEADER(TYPE_NAME, ALIGNEMENT, POCO)
	using TagTypeTraits = ecs::TagTypeTraits;
	using World = ecs::World;
	using TagManager = ecs::TagManager;
	using TagId = ecs::TagId;
	using Entity = ecs::Entity;
	struct TagTypeTraitsInline {
		static const TagTypeTraits *GetTagTypeTraits();

		const static inline char *type_name = "ExampleTagPlayer";
		const static inline std::string name;
		static TagId tag_id;
	};
};


