#pragma once

#include <cstdint>

#include <string>

#include "ecs_types.hpp"

struct ExamplePosition {
	float x, y, z;

	// generated by macro ECS_TYPE_TRAITS_HEADER(TYPE_NAME,
	// SHORT_NAME_OR_INT, POCO=false, ALIGNEMENT=alignof(ExamplePosition))
	static const ecs::TypeTraits *_ecs_get_type_traits();

	constexpr static inline const char *_ecs_type_name = "ExamplePosition";
	constexpr static inline std::string _ecs_name = _ecs_type_name;
	constexpr static inline StringOrInt _ecs_short_type_name_id = {"ep", 0}; // used for serialzation
	constexpr static inline uint32_t _ecs_bytes_size = 12;
	constexpr static inline uint32_t _ecs_alignement = 4;
	constexpr static inline bool _ecs_poco = true;
	static ecs::ComponentId _ecs_component_id;

	static void _ecs_assure(ecs::Entity, ecs::ComponentManager *);
	static ExamplePosition &_ecs_access(ecs::Entity, ecs::ComponentManager *);
	static ExamplePosition &_ecs_add(ecs::Entity, ecs::ComponentManager *);
	static ExamplePosition &_ecs_set(ecs::Entity, ecs::ComponentManager *, const ExamplePosition &val);
	static ExamplePosition &_ecs_set(ecs::Entity, ecs::ComponentManager *, ExamplePosition &&mov_val);
	static ExamplePosition *_ecs_get(ecs::Entity, const ecs::ComponentManager *);
	static void _ecs_remove(ecs::Entity, ecs::ComponentManager *);

	static void _ecs_execute_observers_add(ecs::Entity, ecs::ComponentManager *);
	static void _ecs_execute_observers_set(ecs::Entity, ecs::ComponentManager *);
	static void _ecs_execute_observers_remove(ecs::Entity, ecs::ComponentManager *);

	static void _ecs_move_to_empty(ExamplePosition &&src, ExamplePosition &dst);
	static void _ecs_copy_to_empty(const ExamplePosition &src, ExamplePosition &dst);
	static void _ecs_move_to_existing(ExamplePosition &&src, ExamplePosition &dst);
	static void _ecs_copy_to_existing(const ExamplePosition &src, ExamplePosition *dst);
	static void _ecs_construct(ExamplePosition *ptr);
	static void _ecs_destruct(ExamplePosition *ptr);

	static void _ecs_serialize(struct serializer &ar, const ExamplePosition &ptr);
	// deserialize into existing
	static void _ecs_deserialize(struct deserializer &ar, ExamplePosition &ptr);

	void serialize(struct serializer &ar) const;
	void deserialize(struct deserializer &ar);
};

struct ExampleTagPlayer {
	// generated by macro ECS_TYPE_TRAITS_HEADER(TYPE_NAME, ALIGNEMENT, POCO)
	using TagTypeTraits = ecs::TagTypeTraits;
	using World = ecs::World;
	using TagManager = ecs::TagManager;
	using TagId = ecs::TagId;
	using Entity = ecs::Entity;
	struct TagTypeTraitsInline {
		static const TagTypeTraits *GetTagTypeTraits();

		const static inline char *type_name = "ExampleTagPlayer";
		const static inline std::string name;
		static TagId tag_id;
	};
};


